-- E-258: Scrap consignments — the NBFC → iTarang sale of scrapped batteries.
--
-- WHAT THIS ADDS, AND WHY.
--
-- A battery that fails inspection lands on `nbfc_recovery_pipeline.stage =
-- 'scrap'`, which is a TERMINAL stage with nothing after it: no buyer, no
-- price, no way off the NBFC's books. The auction path (E-227…E-234) only ever
-- serves refurbished stock sold to dealers — scrap is explicitly out of it
-- (Battery Auction BRD §6, "SOH < 55% is scrap"). So the scrap simply
-- accumulated in a column of the Kanban.
--
-- iTarang buys that scrap. This is the deal:
--
--   1. The NBFC picks one or many scrap batteries, attaches photographs, and
--      names a RATE PER BATTERY. That bundle is a consignment.
--   2. iTarang admin sees it, sees the photographs, and answers with its own
--      rate. Either side can counter; every round is kept.
--   3. On acceptance the rate freezes and the amount is rate × battery_count.
--   4. iTarang PAYS the NBFC (RazorpayX payout, or an offline bank transfer
--      recorded by hand) and the batteries transfer to iTarang.
--
-- RATE × COUNT, NOT A PER-BATTERY PRICE LIST. Scrap is bought by the unit at a
-- rate, the way it is actually traded; a 12-battery consignment is one number
-- to argue about, not twelve. `agreed_amount` is still STORED rather than
-- recomputed on read, because the count can only be trusted at the moment the
-- deal was struck.
--
-- THREE TABLES, NOT ONE.
--   scrap_consignments        the deal — status, rates, payment, payee bank
--   scrap_consignment_items   which batteries are in it (the lot)
--   scrap_consignment_offers  APPEND-ONLY round log of who said what
--
-- The offer log is modelled on `nbfc_offer_negotiations` (E-238) for the same
-- reason that table exists: the header row is overwritten with each new rate,
-- so without a log the history a disputed payment turns on is gone. The
-- UNIQUE (consignment_id, round) is a concurrency guard, not tidiness — a round
-- is always current_round + 1, so two simultaneous counters must collide with
-- 23505 rather than both claim round 3.
--
-- WHY `is_open` ON THE ITEMS. A battery must not be sold twice. The rule is
-- "a battery may sit in at most ONE consignment that has not closed", and a
-- partial unique index cannot reach across to the parent's status — so the
-- items carry the open flag themselves and the index enforces it in the
-- database rather than in the service that happens to write it.
--
-- Strictly additive: three new tables, one new nullable column on
-- recovery_batteries. Nothing is dropped, narrowed or backfilled.

-- ---------------------------------------------------------------------------
-- 1. The deal
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scrap_consignments (
  id                     uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Human handle. SCR-000123. Generated by the service, unique so two
  -- concurrent creates cannot mint the same one silently.
  ref_code               varchar(24) NOT NULL,
  tenant_id              uuid NOT NULL,
  -- draft | submitted | negotiating | agreed | paid | rejected | withdrawn
  --
  -- No CHECK, matching every other status column in the recovery/auction
  -- family: the vocabulary lives in TypeScript
  -- (src/lib/nbfc/scrap/consignment.ts) so it can move without a migration
  -- against a drifting database. See the E-232 header for the same decision.
  status                 varchar(24) NOT NULL DEFAULT 'draft',
  -- Denormalised so the inbox can show "12 batteries" without a join, and so
  -- agreed_amount has a count to have been computed from.
  battery_count          integer NOT NULL DEFAULT 0,

  asking_rate_per_battery numeric(12,2),
  agreed_rate_per_battery numeric(12,2),
  agreed_amount           numeric(14,2),

  -- Whose turn it is. `last_party` is who spoke last ('nbfc' | 'admin'), so
  -- the other side is the one that owes an answer.
  current_round          integer NOT NULL DEFAULT 0,
  last_party             varchar(8),

  pickup_city            varchar(120),
  pickup_state           varchar(120),
  warehouse              varchar(160),
  -- Consignment-level photographs: the pile, the weighbridge slip, the gate.
  -- Per-battery shots stay on recovery_batteries.image_urls and are NOT copied
  -- here. Relative /api/files/<bucket>/<key> paths, never absolute URLs.
  photo_urls             text[] NOT NULL DEFAULT '{}'::text[],
  note                   text,

  -- Where iTarang sends the money. Held on the deal rather than on
  -- nbfc_tenants because an NBFC may settle different sales to different
  -- accounts, and because nbfc_tenants carries no bank columns at all.
  payee_name             varchar(160),
  payee_account_number   varchar(40),
  payee_ifsc             varchar(11),

  -- unpaid | processing | paid | failed
  payment_status         varchar(24) NOT NULL DEFAULT 'unpaid',
  -- razorpayx | offline
  payment_provider       varchar(16),
  -- pout_… from RazorpayX, or the operator's bank reference when offline.
  payment_ref            text,
  payment_utr            varchar(64),
  payment_failure_reason text,
  paid_at                timestamptz,
  paid_by                uuid,

  created_by             uuid,
  agreed_by              uuid,
  submitted_at           timestamptz,
  agreed_at              timestamptz,
  closed_at              timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS scrap_consignments_ref_uidx
  ON scrap_consignments (ref_code);
CREATE INDEX IF NOT EXISTS scrap_consignments_tenant_idx
  ON scrap_consignments (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS scrap_consignments_status_idx
  ON scrap_consignments (status, created_at DESC);
-- The admin inbox's default view: everything that is waiting on iTarang.
CREATE INDEX IF NOT EXISTS scrap_consignments_open_idx
  ON scrap_consignments (status)
  WHERE status IN ('submitted', 'negotiating', 'agreed');

-- ---------------------------------------------------------------------------
-- 2. The batteries in it
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scrap_consignment_items (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consignment_id  uuid NOT NULL REFERENCES scrap_consignments(id) ON DELETE CASCADE,
  tenant_id       uuid NOT NULL,
  battery_id      uuid,
  -- Snapshotted, not joined: a serial is what the operator reads off the
  -- casing and what a dispute is argued in, and the battery row can be
  -- re-pointed by a later recovery.
  serial          varchar(64) NOT NULL,
  model           varchar(120),
  capacity        varchar(32),
  soh_pct         numeric(5,2),
  condition_note  text,
  -- TRUE while the parent consignment is live. Flipped to FALSE by the service
  -- when the deal closes (paid / rejected / withdrawn), which is what frees the
  -- battery to be offered again.
  is_open         boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS scrap_consignment_items_consignment_idx
  ON scrap_consignment_items (consignment_id);
CREATE INDEX IF NOT EXISTS scrap_consignment_items_battery_idx
  ON scrap_consignment_items (battery_id);
-- One battery, one open consignment. THE guard against selling the same
-- battery twice; see the header.
CREATE UNIQUE INDEX IF NOT EXISTS scrap_consignment_items_open_battery_uidx
  ON scrap_consignment_items (battery_id)
  WHERE is_open AND battery_id IS NOT NULL;
-- A battery cannot be listed twice inside one consignment either.
CREATE UNIQUE INDEX IF NOT EXISTS scrap_consignment_items_uidx
  ON scrap_consignment_items (consignment_id, battery_id);

-- ---------------------------------------------------------------------------
-- 3. The negotiation, append-only
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scrap_consignment_offers (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  consignment_id   uuid NOT NULL REFERENCES scrap_consignments(id) ON DELETE CASCADE,
  tenant_id        uuid NOT NULL,
  round            integer NOT NULL,
  -- 'nbfc' | 'admin'
  party            varchar(8) NOT NULL,
  -- quote | counter | accept | reject | withdraw
  kind             varchar(16) NOT NULL,
  rate_per_battery numeric(12,2),
  battery_count    integer,
  amount           numeric(14,2),
  message          text,
  created_by       uuid,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS scrap_consignment_offers_round_uidx
  ON scrap_consignment_offers (consignment_id, round);
CREATE INDEX IF NOT EXISTS scrap_consignment_offers_consignment_idx
  ON scrap_consignment_offers (consignment_id, created_at);

-- ---------------------------------------------------------------------------
-- 4. The battery's side of the link
-- ---------------------------------------------------------------------------
-- Set when a consignment is PAID. It is what turns "state_code = 'scrapped'"
-- from a bare status into "sold to iTarang under SCR-000123 for ₹8,000", which
-- is the question anyone auditing a scrapped battery actually asks.
ALTER TABLE recovery_batteries
  ADD COLUMN IF NOT EXISTS scrap_consignment_id uuid;

CREATE INDEX IF NOT EXISTS recovery_batteries_scrap_consignment_idx
  ON recovery_batteries (scrap_consignment_id);

-- ---------------------------------------------------------------------------
-- Self-documentation
-- ---------------------------------------------------------------------------
COMMENT ON TABLE scrap_consignments IS
  'E-258: one NBFC → iTarang sale of scrapped batteries. status: draft|submitted|negotiating|agreed|paid|rejected|withdrawn. Price is a rate per battery; agreed_amount = agreed_rate_per_battery × battery_count frozen at acceptance.';
COMMENT ON COLUMN scrap_consignments.last_party IS
  'Who spoke last (nbfc|admin) — the OTHER side owes the next answer.';
COMMENT ON COLUMN scrap_consignments.payment_status IS
  'unpaid|processing|paid|failed. processing = a RazorpayX payout is queued/pending and its terminal state has not been read back yet.';
COMMENT ON TABLE scrap_consignment_items IS
  'E-258: the batteries in one consignment. is_open=true while the parent deal is live; the partial unique index on (battery_id) WHERE is_open is what stops one battery being sold twice.';
COMMENT ON TABLE scrap_consignment_offers IS
  'E-258: append-only negotiation log, one row per round. Modelled on nbfc_offer_negotiations (E-238) — the header row is overwritten on each counter, so this is where the history lives.';
COMMENT ON COLUMN recovery_batteries.scrap_consignment_id IS
  'E-258: set when the battery was sold to iTarang as scrap under this consignment.';
