/**
 * Regenerate docs/nbfc/_convergence/journey_index.md from manifest.json.
 *
 * Produces a one-page human-readable index of every executable unit in the
 * full-BRD headed journey, grouped by persona/section.
 *
 *   npx tsx scripts/regen_journey_index.ts
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

type ManifestUnit = {
  id: string;
  slug?: string;
  name?: string;
  status?: string;
  source_section?: string;
  source_brd?: string;
  headed_test_status?: string;
};

type Manifest = { units: Record<string, ManifestUnit> };

const ROOT = path.resolve(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'docs/nbfc/manifest.json');
const OUT_PATH = path.join(ROOT, 'docs/nbfc/_convergence/journey_index.md');

const PERSONA_BLOCKS: Array<{ block: string; persona: string; section: string; ids: string[] }> = [
  { block: 'A', persona: 'itarang_super_admin', section: '§6.0 admin onboarding pipeline',
    ids: ['E-001', 'E-002', 'E-003', 'E-004', 'E-005', 'E-006', 'E-007', 'E-008', 'E-009', 'E-010', 'E-011', 'E-012', 'E-013'] },
  { block: 'B', persona: 'nbfc_tenant_user', section: '§6.1.2-4 tenant portal nav / portfolio / leads',
    ids: ['E-025', 'E-026', 'E-027', 'E-028'] },
  { block: 'C', persona: 'itarang_super_admin', section: '§6.1.5 admin nightly score compute',
    ids: ['E-029', 'E-030'] },
  { block: 'D', persona: 'nbfc_tenant_user', section: '§6.1.6-7 tenant risk actions + recovery + auction',
    ids: ['E-031', 'E-032', 'E-033', 'E-034', 'E-035', 'E-036', 'E-037', 'E-038', 'E-039'] },
  { block: 'E', persona: 'itarang_super_admin', section: '§6.2 telemetry plane',
    ids: ['E-045', 'E-046', 'E-047', 'E-048', 'E-049', 'E-050', 'E-051'] },
  { block: 'F', persona: 'itarang_super_admin', section: '§6.3 admin ecosystem / risk rules / audit log',
    ids: ['E-065', 'E-066', 'E-067', 'E-068', 'E-069', 'E-070', 'E-071', 'E-072'] },
  { block: 'G', persona: 'kyc_reviewer', section: '§6.3.3 second-approver releases pending change',
    ids: ['E-068'] },
  { block: 'H', persona: 'nbfc_tenant_user', section: '§6.4.2-3 compliance + dual-approval primitive',
    ids: ['E-080', 'E-081', 'E-082', 'E-083', 'E-084', 'E-085', 'E-086', 'E-087', 'E-088', 'E-089'] },
  { block: 'I', persona: 'nbfc_tenant_user', section: '§6.4.4-5 DPDPA consent + score explainability',
    ids: ['E-090', 'E-091', 'E-092', 'E-093'] },
  { block: 'J', persona: 'itarang_super_admin', section: '§6.4.4 admin DPDPA retention job',
    ids: ['E-091'] },
  { block: 'K', persona: 'itarang_super_admin', section: 'sync-audit cross-cutting (canonical schemas / endpoints / utilities)',
    ids: ['E-100', 'E-101', 'E-102', 'E-103', 'E-104', 'E-105'] },
];

function loadManifest(): Manifest {
  return JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
}

function badge(status: string | undefined): string {
  if (!status) return ':grey_question:';
  if (/^pass/i.test(status)) return ':white_check_mark:';
  if (/^block/i.test(status)) return ':no_entry:';
  if (/^superseded/i.test(status)) return ':leftwards_arrow_with_hook:';
  if (/fail/i.test(status)) return ':x:';
  return ':hourglass:';
}

function main() {
  const manifest = loadManifest();
  const seen = new Set<string>();

  const lines: string[] = [];
  lines.push('# NBFC Section 6 — full-BRD headed journey index');
  lines.push('');
  lines.push('_Auto-generated by `scripts/regen_journey_index.ts` from `docs/nbfc/manifest.json`._');
  lines.push('');
  lines.push(`Generated: ${new Date().toISOString()}`);
  lines.push('');
  lines.push('## Run the journey');
  lines.push('');
  lines.push('```sh');
  lines.push('# Cold start (wipes resume state):');
  lines.push('RESET_JOURNEY=1 HEADED=1 NBFC_E2E_PAUSE_ON_FAIL=1 \\');
  lines.push('  NBFC_E2E_RAW_JSONL=docs/nbfc/_convergence/journey.jsonl \\');
  lines.push('  npx playwright test tests/e2e/nbfc/_journey_full_brd.headed.spec.ts \\');
  lines.push('  --project=chromium-manual --reporter=list');
  lines.push('');
  lines.push('# Resume from a specific AC after a fix:');
  lines.push('RESUME_FROM=E-007:AC2 HEADED=1 NBFC_E2E_PAUSE_ON_FAIL=1 \\');
  lines.push('  NBFC_E2E_RAW_JSONL=docs/nbfc/_convergence/journey.jsonl \\');
  lines.push('  npx playwright test tests/e2e/nbfc/_journey_full_brd.headed.spec.ts \\');
  lines.push('  --project=chromium-manual --reporter=list');
  lines.push('```');
  lines.push('');
  lines.push('## Flow map');
  lines.push('');

  for (const { block, persona, section, ids } of PERSONA_BLOCKS) {
    lines.push(`### Block ${block} — ${section}`);
    lines.push('');
    lines.push(`Persona: \`${persona}\``);
    lines.push('');
    lines.push('| Unit | Status | Section | Name |');
    lines.push('| --- | --- | --- | --- |');
    for (const id of ids) {
      const u = manifest.units[id];
      seen.add(id);
      if (!u) {
        lines.push(`| ${id} | :grey_question: | — | _missing from manifest_ |`);
        continue;
      }
      const name = (u.name ?? '').replace(/\|/g, '\\|');
      lines.push(`| ${id} | ${badge(u.status)} ${u.status ?? ''} | ${u.source_section ?? ''} | ${name} |`);
    }
    lines.push('');
  }

  // Catch any manifest unit we forgot to map into a block.
  const orphaned = Object.keys(manifest.units).filter((id) => !seen.has(id));
  if (orphaned.length) {
    lines.push('### :warning: Orphan units (in manifest but not in any block)');
    lines.push('');
    lines.push('| Unit | Status | Section | Name |');
    lines.push('| --- | --- | --- | --- |');
    for (const id of orphaned) {
      const u = manifest.units[id];
      const name = (u.name ?? '').replace(/\|/g, '\\|');
      lines.push(`| ${id} | ${badge(u.status)} ${u.status ?? ''} | ${u.source_section ?? ''} | ${name} |`);
    }
    lines.push('');
  }

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`wrote ${OUT_PATH} (${lines.length} lines, ${seen.size} units in blocks, ${orphaned.length} orphan)`);
}

main();
