/**
 * E-003 — NBFC master details — create / read / update endpoints and admin form
 * Source: 6.0.3
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-003`;

test.describe('E-003 headed — NBFC master details — create / read / update endpoints and admin form', () => {
  test.describe('E-003 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: POST /api/admin/nbfc with all required fields returns 200 and persists a row with auto-generated nbfc_id of format \'N…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · GET /api/admin/nbfc/1</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: POST /api/admin/nbfc returns 422 when grievance_officer_name, grievance_helpline, or grievance_url is missing.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · GET /api/admin/nbfc/1</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: POST /api/admin/nbfc with a duplicate rbi_registration_no returns 409 and does not create a row.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · GET /api/admin/nbfc/1</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
    test('AC4: GET /api/admin/nbfc/{id} returns the master record with the same nbfc_id and legalName that was created.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC4 · GET /api/admin/nbfc/1</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC4_step1.png`, fullPage: true });
    });
  });
});
