/**
 * E-001 — NBFC final approval gate — block activation until all compliance docs verified and LSP Agreement COMPLETED
 * Source: 6.0.2
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-001`;

test.describe('E-001 headed — NBFC final approval gate — block activation until all compliance docs verified and LSP Agreement COMPLETED', () => {
  test.describe('E-001 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: POST /api/admin/nbfc/{nbfcId}/approve returns 422 when any required compliance document is missing or unverified.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1/approval-readiness', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · GET /api/admin/nbfc/1/approval-readiness</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: POST /api/admin/nbfc/{nbfcId}/approve returns 422 when linked nbfc_lsp_agreements.agreement_status != \'COMPLETED\'.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1/approval-readiness', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · GET /api/admin/nbfc/1/approval-readiness</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: When all docs verified and LSP COMPLETED, POST returns 200 and nbfc.status is updated to \'approved\' in DB.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/admin/nbfc/1/approval-readiness', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · GET /api/admin/nbfc/1/approval-readiness</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
    test('AC4: Admin review page disables the Approve button and shows tooltip \'Cannot activate until LSP Agreement is fully signed …', async ({ page }) => {
    await page.goto('/admin/nbfc/1/review', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {});
    await expect(page.locator('body')).toBeVisible({ timeout: 8000 });
    await page.screenshot({ path: `${HEADED_DIR}/AC4_step1.png`, fullPage: true });
    });
  });
});
