/**
 * E-025 — NBFC portal sidebar navigation shell
 * Source: 6.1.2
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-025`;

test.describe('E-025 headed — NBFC portal sidebar navigation shell', () => {
  test.describe('E-025 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: Sidebar renders all seven items in the order: Portfolio Overview, Lead Intelligence, Battery Monitoring, Risk Alerts,…', async ({ page }) => {
    await page.goto('/nbfc', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {});
    await expect(page.locator('body')).toBeVisible({ timeout: 8000 });
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: Clicking the Portfolio Overview item navigates the user to /nbfc/portfolio.', async ({ page }) => {
    await page.goto('/nbfc', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {});
    await expect(page.locator('body')).toBeVisible({ timeout: 8000 });
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: When the current path starts with /nbfc/recovery the Recovery & Auction item has the active visual state.', async ({ page }) => {
    await page.goto('/nbfc', { waitUntil: 'domcontentloaded', timeout: 15000 }).catch(() => {});
    await expect(page.locator('body')).toBeVisible({ timeout: 8000 });
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
  });
});
