/**
 * E-029 — CDS nightly computation job
 * Source: 6.1.5
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-029`;

test.describe('E-029 headed — CDS nightly computation job', () => {
  test.describe('E-029 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: POST /api/cron/nbfc/compute-cds returns 200 with computed_count, skipped_count, and run_at ISO timestamp.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/cron/nbfc/compute-cds', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · POST /api/cron/nbfc/compute-cds</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: After the job runs, borrower_risk_scores has a fresh row with computed_at = now for each active loan_sanction.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/cron/nbfc/compute-cds', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · POST /api/cron/nbfc/compute-cds</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: A borrower with fewer than 3 EMI records is recorded with confidence=\'LOW\'.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/cron/nbfc/compute-cds', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · POST /api/cron/nbfc/compute-cds</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
    test('AC4: A borrower with 6+ EMI records and telemetry ingestion within the last 12 hours is recorded with confidence=\'HIGH\'.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/cron/nbfc/compute-cds', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC4 · POST /api/cron/nbfc/compute-cds</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC4_step1.png`, fullPage: true });
    });
    test('AC5: Computed cds_score is always in the closed range [0, 100].', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/cron/nbfc/compute-cds', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC5 · POST /api/cron/nbfc/compute-cds</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC5_step1.png`, fullPage: true });
    });
  });
});
