/**
 * E-045 — IoT device registration on inventory upload
 * Source: 6.2.2
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-045`;

test.describe('E-045 headed — IoT device registration on inventory upload', () => {
  test.describe('E-045 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: POST /api/iot/register-device with valid body inserts a new iot_devices row with device_status=\'registered\' and retur…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/iot/register-device', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · POST /api/iot/register-device</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: Repeated POST /api/iot/register-device with the same serialNumber and imeiId does not create a duplicate row and retu…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/iot/register-device', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · POST /api/iot/register-device</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: POST /api/iot/register-device with imeiId that is not 15–20 digits returns HTTP 422.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/iot/register-device', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · POST /api/iot/register-device</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
  });
});
