/**
 * E-085 — Risk rule threshold change gated by dual approval (iTarang Admin → Risk Head/Super Admin)
 * Source: 6.4.3
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-085`;

test.describe('E-085 headed — Risk rule threshold change gated by dual approval (iTarang Admin → Risk Head/Super Admin)', () => {
  test.describe('E-085 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: POST /api/nbfc/actions/risk-rule-threshold/initiate by an iTarang Admin returns 200 with approval_request_id and stat…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/nbfc/actions/risk-rule-threshold/initiate', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · POST /api/nbfc/actions/risk-rule-threshold/initiate</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: POST initiate by a non-admin user returns 403.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/nbfc/actions/risk-rule-threshold/initiate', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · POST /api/nbfc/actions/risk-rule-threshold/initiate</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: After approval by an iTarang Risk Head or Super Admin user, exactly one new row in nbfc_risk_rule_thresholds exists w…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.post('/api/nbfc/actions/risk-rule-threshold/initiate', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · POST /api/nbfc/actions/risk-rule-threshold/initiate</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
  });
});
