/**
 * E-100 — Canonical inventory categories endpoint — flat 6-code category list with battery model arrays (no vehicle-type sub-categories)
 * Source: sync-audit-G-01
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-100`;

test.describe('E-100 headed — Canonical inventory categories endpoint — flat 6-code category list with battery model arrays (no vehicle-type sub-categories)', () => {
  test.describe('E-100 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: GET /api/inventory/categories returns 200 with exactly six entries whose codes are 3W, INV, 2W, 4W, SOL, OTH.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/inventory/categories', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · GET /api/inventory/categories</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: Response entry for code=\'3W\' has models array equal to [\'51.2V-105AH\',\'51.2V-140AH\',\'51.2V-153AH\',\'60.8V-105AH\',\'60.8…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/inventory/categories', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · GET /api/inventory/categories</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: Response entry for code=\'INV\' has models array equal to [\'Power Cube 1.4\',\'Power Cube 1.4+\',\'Power Cube 2.7\',\'Power C…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/inventory/categories', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · GET /api/inventory/categories</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
    test('AC4: Response entries for codes 2W, 4W, SOL, OTH each have models=[] (empty array).', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/inventory/categories', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC4 · GET /api/inventory/categories</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC4_step1.png`, fullPage: true });
    });
    test('AC5: Response JSON does not contain any field named \'subCategories\' or \'sub_category\' at any level.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/api/inventory/categories', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC5 · GET /api/inventory/categories</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC5_step1.png`, fullPage: true });
    });
  });
});
