/**
 * E-104 — inventory_transfers — bundled spec: define base table AND rejection extension (G-06 resolution)
 * Source: sync-audit-G-06
 * Headed visual layer for /nbfc convergence Stage 5h.
 * Generated by /tmp/gen_headed_specs.py — do not hand-edit.
 * Persona-grouped + assertion-bearing per Phase 0.2.
 */
import { test, expect } from '@playwright/test';

const HEADED_DIR = `docs/nbfc/headed_tests/E-104`;

test.describe('E-104 headed — inventory_transfers — bundled spec: define base table AND rejection extension (G-06 resolution)', () => {
  test.describe('E-104 · persona=itarang_super_admin', () => {
    test.use({ storageState: 'tests/.auth/itarang_super_admin.json' });
    test('AC1: After migration, inventory_transfers exists with columns id, transfer_id, source_dealer_id, target_dealer_id, serials…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC1 · GET /</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC1_step1.png`, fullPage: true });
    });
    test('AC2: After migration, inventory_transfers.status accepts the values \'pending_acknowledgement\', \'completed\', \'rejected_by_t…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC2 · GET /</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC2_step1.png`, fullPage: true });
    });
    test('AC3: An INSERT with any partial subset of (rejected_by, rejected_at, rejection_reason) non-null fails the all-or-nothing C…', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC3 · GET /</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC3_step1.png`, fullPage: true });
    });
    test('AC4: transfer_id has a UNIQUE constraint — inserting two rows with the same transfer_id fails.', async ({ page, request }) => {
    let body: any = null;
    let status = 0;
    try {
      const res = await request.get('/', { data: {}, timeout: 10000 });
      status = res.status();
      try { body = await res.json(); } catch { body = await res.text(); }
    } catch (e) { body = String(e); }
    expect(status).toBeGreaterThan(0);
    const html = `<!doctype html><html><body style="font:13px/1.4 ui-monospace,monospace;padding:12px"><h2 style="margin:0 0 8px">AC4 · GET /</h2><div data-testid="api-status">HTTP ${status}</div><pre data-testid="api-response" style="background:#f4f4f4;padding:10px;white-space:pre-wrap">${typeof body === 'string' ? body : JSON.stringify(body, null, 2)}</pre></body></html>`;
    await page.setContent(html);
    await page.screenshot({ path: `${HEADED_DIR}/AC4_step1.png`, fullPage: true });
    });
  });
});
